# Generated by Django 5.1.7 on 2025-03-12 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('rank', models.IntegerField()),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='core.employee')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('attendees', models.ManyToManyField(blank=True, related_name='courses', to='core.employee')),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='EmployeeReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_to', to='core.employee')),
                ('reporter_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_by', to='core.employee')),
            ],
            options={
                'db_table': 'employee_reports',
                'unique_together': {('reporter_employee', 'reported_employee')},
            },
        ),
        migrations.CreateModel(
            name='RoleHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_by', to='core.role')),
                ('reporter_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_to', to='core.role')),
            ],
            options={
                'db_table': 'role_hierarchy',
                'constraints': [models.UniqueConstraint(fields=('reporter_role', 'reported_role'), name='unique_role_hierarchy')],
            },
        ),
    ]
