# Generated by Django 5.1.7 on 2025-03-13 18:04

from django.db import migrations

def insert_role_hierarchy(apps, schema_editor):
    Role = apps.get_model('core', 'Role')
    RoleHierarchy = apps.get_model('core', 'RoleHierarchy')

    # Get the role instances by their titles
    gm = Role.objects.get(title="General Manager")
    director = Role.objects.get(title="Director")
    team_leader = Role.objects.get(title="Team Leader")
    programmer = Role.objects.get(title="Programmer")

    # Populate role hierarchy based on the rules
    RoleHierarchy.objects.bulk_create([
        # Directors -> GM
        RoleHierarchy(reporter_role=director, reported_role=gm),
        # Team Leaders -> Directors
        RoleHierarchy(reporter_role=team_leader, reported_role=director),
        # Programmers -> Directors
        RoleHierarchy(reporter_role=programmer, reported_role=director),
        # Programmers -> Team Leaders
        RoleHierarchy(reporter_role=programmer, reported_role=team_leader),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_populate_roles'),
    ]

    operations = [
        migrations.RunPython(insert_role_hierarchy),
    ]
